* Similarity

** Overview

A Ruby library for calculating the similarity between pieces of text
using a [[http://en.wikipedia.org/wiki/Tf%25E2%2580%2593idf][Term Frequency-Inverse Document Frequency]] method.

A [[http://en.wikipedia.org/wiki/Bag_of_words_model][bag of words]] model is used. Terms in the source documents are
downcased and punctuation is removed, but stemming is not currently
implemented.

This library was written to facilitate the creation of diagrams talked
about by Jonathan Stray in his
[[http://jonathanstray.com/a-full-text-visualization-of-the-iraq-war-logs][full-text
visualization of the Iraq War Logs]] post. An example of how to
generate a [[http://gephi.org/][Gephi]] compatible file including labelling of nodes with key
words is included in the =examples= directory.

The library depends on the [[http://www.gnu.org/software/gsl/][GNU Scientific Library]], and the [[http://rb-gsl.rubyforge.org/][gsl ruby
gem]] but does not use sparse matrix representations to speed up the
calculations, since there is no support for them in the GSL. I am
currently looking into fixing this, and would appreciate any help!

** Dependencies

Similarity depends on the [[http://www.gnu.org/software/gsl/][GNU Scientific Library]], and the [[http://rb-gsl.rubyforge.org/][gsl ruby
gem]]. On OSX with [[https://github.com/mxcl/homebrew]] the GSL can be
installed with

: brew install gsl

The =gsl= gem should then install normally. For other platforms,
please add the information to the wiki and I'll add them to this
readme.

** Usage

: require 'similarity'
:
: corpus = Corpus.new
:
: corpus << Document.new("Broad powers for hacking inquiry")
: corpus << Document.new("UK unemployment level falls again")
: corpus << Document.new("NI riots leads to 26 arrests")
:
: similarity_matrix = corpus.similarity_matrix

For more examples, see the =examples= directory.

** Todo
- Performance improvements
  - Switch to storing document vector spaces in sparse form, using linalg or csparse?
- (Optional) stemming of source terms

** Contributing
- Fork the project
- Send a pull request
- Don't touch the .gemspec, I'll do that when I release a new version

** Author

[[http://chrislowis.co.uk][Chris Lowis]] - BBC R&D

